/// @description Insert description here
// You can write your code in this editor
showText = false;  // This controls the visibility of the text bubble
text = "Polypropylene fragments: Irregular shaped fragments generated by breakdown of larger plastic debris";  // The message to display